// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqXWHWWq9X-0bzx--5io1WQmve4u4whsE',
    appId: '1:132776268658:web:ae4817644cd394f783c3eb',
    messagingSenderId: '132776268658',
    projectId: 'chatapp-ed14d',
    authDomain: 'chatapp-ed14d.firebaseapp.com',
    storageBucket: 'chatapp-ed14d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU_sHiZPwQVKm_6LYNSaYy7Oz4wH2Qf3g',
    appId: '1:132776268658:android:c119f76e97e2eda183c3eb',
    messagingSenderId: '132776268658',
    projectId: 'chatapp-ed14d',
    storageBucket: 'chatapp-ed14d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzTJgoe_A_mSv2mpUcEUO419hek-tfg74',
    appId: '1:132776268658:ios:6212bd278b613b3083c3eb',
    messagingSenderId: '132776268658',
    projectId: 'chatapp-ed14d',
    storageBucket: 'chatapp-ed14d.appspot.com',
    androidClientId: '132776268658-2ci5c1v0vdsjpr0vvdmu2qn063rmv30p.apps.googleusercontent.com',
    iosClientId: '132776268658-un0j8fodc0u7nqugh0md69p200sfmvme.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzTJgoe_A_mSv2mpUcEUO419hek-tfg74',
    appId: '1:132776268658:ios:6212bd278b613b3083c3eb',
    messagingSenderId: '132776268658',
    projectId: 'chatapp-ed14d',
    storageBucket: 'chatapp-ed14d.appspot.com',
    androidClientId: '132776268658-2ci5c1v0vdsjpr0vvdmu2qn063rmv30p.apps.googleusercontent.com',
    iosClientId: '132776268658-un0j8fodc0u7nqugh0md69p200sfmvme.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
